name: Release to JSR and NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Publish package
        run: npx jsr publish

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get Version
        id: vars
        run: echo "version=${{ github.ref_name }}" | sed 's/^v//' >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.com

      - name: Build
        run: deno task build:npm $NPM_VERSION
        env:
          NPM_VERSION: ${{ env.version }}

      - name: Publish
        run: npm publish --access=public
        working-directory: ./build/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
